---
language: shell
services:
  - docker

# Environment variables defined as part of the Travis CI repository configuration are:
# - DOCKER_ORG: the docker hub organization (or user) to which the image will be pushed
# - DOCKER_USER: the docker hub user used to log in to the docker hub
# - DOCKER_PASS: the password of this user

env:
  global:
    - IMAGE_NAME="${DOCKER_ORG}/nansat_base"
    - DOCKER_TMP_TAG='tmp'

jobs:
  include:
    - stage: 'Build Docker images'
      name: 'Build standard image'
      install:
        - docker pull "${IMAGE_NAME}" || true
      script:
        - >
          docker build .
          --cache-from "${IMAGE_NAME}"
          -t "${IMAGE_NAME}:${DOCKER_TMP_TAG}"
        # Basic test
        - docker run --rm "${IMAGE_NAME}:${DOCKER_TMP_TAG}" python -c 'import gdal'
      before_deploy:
        - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      deploy:
        provider: script
        on:
          tags: true
        script: /bin/bash docker_push.sh "${IMAGE_NAME}" ''

    - name: 'Build slim image'
      env:
        - COMPILE_STAGE_SUFFIX='-compile-stage'
        - SLIM_SUFFIX='-slim'
      install:
        - docker pull "${IMAGE_NAME}:latest${COMPILE_STAGE_SUFFIX}" || true
        - docker pull "${IMAGE_NAME}:latest${SLIM_SUFFIX}" || true
      script:
        - >
          docker build .
          -f Dockerfile_slim --target builder
          --cache-from "${IMAGE_NAME}:latest${COMPILE_STAGE_SUFFIX}"
          -t "${IMAGE_NAME}:${DOCKER_TMP_TAG}${COMPILE_STAGE_SUFFIX}"
        - >
          docker build .
          -f Dockerfile_slim
          --cache-from "${IMAGE_NAME}:${DOCKER_TMP_TAG}${COMPILE_STAGE_SUFFIX}"
          --cache-from "${IMAGE_NAME}:latest${SLIM_SUFFIX}"
          -t "${IMAGE_NAME}:${DOCKER_TMP_TAG}${SLIM_SUFFIX}"
        # Basic test
        - docker run --rm "${IMAGE_NAME}:${DOCKER_TMP_TAG}${SLIM_SUFFIX}" python -c 'import gdal'
      before_deploy:
        - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      deploy:
        provider: script
        on:
          tags: true
        script: /bin/bash docker_push.sh "${IMAGE_NAME}" "${COMPILE_STAGE_SUFFIX}" "${SLIM_SUFFIX}"
...