---
language: shell
services:
  - docker

# Environment variables defined as part of the Travis CI repository configuration are:
# - DOCKER_ORG: the docker hub organization (or user) to which the image will be pushed
# - DOCKER_USER: the docker hub user used to log in to the docker hub
# - DOCKER_PASS: the password of this user

env:
  global:
    - IMAGE_NAME="${DOCKER_ORG}/nansat_base"
    - DOCKER_TMP_TAG='tmp'

install:
  - docker pull "${IMAGE_NAME}" || true

script:
  - >
    docker build .
    --cache-from "${IMAGE_NAME}"
    -t "${IMAGE_NAME}:${DOCKER_TMP_TAG}"
  # Basic test
  - docker run --rm "${IMAGE_NAME}:${DOCKER_TMP_TAG}" python -c 'import gdal'

before_deploy:
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"

deploy:
  provider: script
  on:
    tags: true
  script: /bin/bash docker_push.sh "${TRAVIS_TAG}" latest
...